## <font color="maroon"><h4 align="center"> DataFrame Basics (Exercise)</font>

**Peter Pandey** arrived in Bangalore(a city in India) with the aim of finding a suitable house that fits his budget and location preferences. He has some queries related to house selection and is seeking solutions.

Help Peter Pandey to answer his questions and you are provided with a sample dataset of house information that contain area_type, availability, location, size, society, total_sqft, bath, balcony, and price.

In [2]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file 'bengaluru_house_prices.csv' and store it in variable 'df'.
- print the number of rows and columns in it
- print the Top 5 rows

In [3]:
#read the csv file

df=pd.read_csv("bengaluru_house_prices.csv")

#show the number of rows and columns in dataframe 'df'
df.shape

#show Top5 rows
df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,Ready To Move,Ambedkar Nagar,3 BHK,NaN,1920,4.0,2.0,121.0
1,Plot Area,18-Aug,Hulimavu,4 Bedroom,ValleCi,1500,4.0,3.0,192.0
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.0
3,Plot Area,Ready To Move,Kodigehalli,2 Bedroom,NaN,500,1.0,0.0,55.0
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.0

### <font color="purple">**Question2**</font>
- show the unique categories present in **'area_type'** and **'size'** columns

In [4]:
#unique values in 'area_type' column
df.area_type.unique()

<StringArray>
['Super built-up  Area', 'Plot  Area', 'Built-up  Area', 'Carpet  Area']
Length: 4, dtype: str

In [5]:
#unique values in 'size' column
df['size'].unique()
#Here df.size.unique() -> error, size is a function.

<StringArray>
[    '3 BHK', '4 Bedroom',     '2 BHK', '2 Bedroom',     '1 BHK',     '5 BHK',
 '3 Bedroom', '5 Bedroom', '1 Bedroom']
Length: 9, dtype: str

In [11]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'area_type',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'availability',
 'axes',
 'balcony',
 'bath',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'location',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'price',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'society',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'total_sqft',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [18]:
df.count(axis=0)

area_type       50
availability    50
location        50
size            50
society         30
total_sqft      50
bath            50
balcony         50
price           50
dtype: int64

### <font color="purple">**Question3**</font>
- Filter data which have **'2 BHK'** house size and area_type of **'Super built-up  Area'**
- Also get the count of such rows

In [30]:
#filter the data
df_f=df[(df['size']=='2 BHK') & (df['area_type']=='Super built-up  Area')]
df_f

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.00
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.00
5,Super built-up Area,Ready To Move,Jakkur,2 BHK,HRaniIb,1202,2.0,1.0,79.00
8,Super built-up Area,Ready To Move,Thubarahalli,2 BHK,ShdhiSa,1200,2.0,2.0,79.55
11,Super built-up Area,17-Oct,Ramagondanahalli,2 BHK,ViistLa,1235,2.0,1.0,52.04
14,Super built-up Area,Ready To Move,Budigere,2 BHK,PrityTr,1153,2.0,2.0,56.55
21,Super built-up Area,18-Apr,Sai Gardens,2 BHK,NaN,1120,2.0,2.0,40.00
24,Super built-up Area,Ready To Move,Neeladri Nagar,2 BHK,GeereEc,1363,2.0,2.0,68.00
25,Super built-up Area,Ready To Move,Sarjapur,2 BHK,NaN,1175,2.0,2.0,42.00
32,Super built-up Area,Ready To Move,Yelahanka,2 BHK,Pyikad,1274,2.0,2.0,48.42
33,Super built-up Area,Ready To Move,AECS Layout,2 BHK,CMard B,1005,2.0,1.0,55.00
35,Super built-up Area,17-Mar,Varthur,2 BHK,Uptusol,1385,2.0,3.0,80.00
37,Super built-up Area,Ready To Move,Seegehalli,2 BHK,Sriferi,1176,2.0,2.0,50.00
38,Super built-up Area,Ready To Move,Electronic City,2 BHK,GMown E,770,1.0,1.0,40.00
39,Super built-up Area,Ready To Move,Banashankari,2 BHK,NaN,1195,2.0,1.0,35.84
41,Super built-up Area,Ready To Move,Kambipura,2 BHK,Prrtht,883,2.0,1.0,37.00
42,Super built-up Area,Ready To Move,Haralur Road,2 BHK,RInceeg,1243,2.0,2.0,46.00
45,Super built-up Area,Ready To Move,Basavangudi,2 BHK,NaN,1200,2.0,3.0,120.00
48,Super built-up Area,Ready To Move,Choodasandra,2 BHK,Maidsr,1075,2.0,2.0,45.00
49,Super built-up Area,Ready To Move,Doctors Layout,2 BHK,NaN,1225,2.0,1.0,47.00

In [31]:
#show the number of rows for the filtered data
df_f.count()

area_type       20
availability    20
location        20
size            20
society         15
total_sqft      20
bath            20
balcony         20
price           20
dtype: int64

In [32]:
len(df_f)

20

### <font color="purple">**Question4**</font>
- Add a new column **'price_category'** which contain a category based on the price of house.
- If price of house is less than 80, **"Affordable"**, otherwise **"High Cost"**

In [34]:
#Add the column 'price_category'
def verdict(x):
    if x<80:
        return "Affordable"
    else:
        return "High Cost"

df['price_category'] = df['price'].apply(verdict)

In [35]:
#show the updated dataframe: top5 rows
df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,price_category
0,Super built-up Area,Ready To Move,Ambedkar Nagar,3 BHK,NaN,1920,4.0,2.0,121.0,High Cost
1,Plot Area,18-Aug,Hulimavu,4 Bedroom,ValleCi,1500,4.0,3.0,192.0,High Cost
2,Super built-up Area,Ready To Move,Kalkere,2 BHK,Sothin,925,2.0,1.0,55.0,Affordable
3,Plot Area,Ready To Move,Kodigehalli,2 Bedroom,NaN,500,1.0,0.0,55.0,Affordable
4,Super built-up Area,Ready To Move,Harlur,2 BHK,Prncyrn,1174,2.0,1.0,74.0,Affordable

### <font color="purple">**Question5**</font>

- Get all the rows that has prices greater than **mean/average** price of all houses

In [38]:
#write condition here
df[(df['price'])>(df['price'].mean())]

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,price_category
0,Super built-up Area,Ready To Move,Ambedkar Nagar,3 BHK,NaN,1920,4.0,2.0,121.0,High Cost
1,Plot Area,18-Aug,Hulimavu,4 Bedroom,ValleCi,1500,4.0,3.0,192.0,High Cost
9,Plot Area,Ready To Move,Whitefield,4 Bedroom,Adowslm,3100,4.0,2.0,350.0,High Cost
16,Super built-up Area,18-Dec,Hebbal,3 BHK,Mahosya,1920,3.0,2.0,134.0,High Cost
18,Built-up Area,Ready To Move,Rayasandra,5 BHK,NaN,3600,5.0,3.0,145.0,High Cost
20,Super built-up Area,Ready To Move,HRBR Layout,3 BHK,VDenaWa,2800,3.0,2.0,250.0,High Cost
26,Super built-up Area,Ready To Move,Jakkur,3 BHK,BrdgeNo,1710,3.0,2.0,110.0,High Cost
27,Carpet Area,Ready To Move,Maruthi Sevanagar,4 Bedroom,NaN,2100,3.0,0.0,210.0,High Cost
31,Super built-up Area,Ready To Move,Tumkur Road,3 BHK,Sahtsva,1354,3.0,1.0,90.0,High Cost
40,Plot Area,Ready To Move,Karuna Nagar,3 Bedroom,CoinoCu,2500,3.0,2.0,190.0,High Cost
43,Built-up Area,Ready To Move,Vishwapriya Layout,5 Bedroom,NaN,2800,5.0,3.0,130.0,High Cost
45,Super built-up Area,Ready To Move,Basavangudi,2 BHK,NaN,1200,2.0,3.0,120.0,High Cost